slate:
	raml2html --theme 'raml2html-slate-theme' -o 'tourlocus-api.html' -i 'tourlocus.raml'
material:
	raml2html --theme 'raml2html-material-theme' -o 'tourlocus-api.html' -i 'tourlocus.raml'
kaa:
		raml2html --theme 'raml2html-kaa-theme' -o 'tourlocus-api.html' -i 'tourlocus.raml'
default:
	raml2html 'tourlocus.raml' > 'tourlocus-api.html'
